#pragma once

// NumPP umbrella header — a single include for the public API.
#include "numpp/version.hpp"
#include "numpp/export.hpp"
#include "numpp/core/error.hpp"
#include "numpp/core/half.hpp"
#include "numpp/core/dtype.hpp"
#include "numpp/core/shape.hpp"
#include "numpp/core/ndarray.hpp"
#include "numpp/core/creation.hpp"
#include "numpp/manip/manip.hpp"
#include "numpp/stats/stats.hpp"
#include "numpp/grids/grids.hpp"
#include "numpp/umath/ufunc.hpp"
#include "numpp/linalg/linalg.hpp"
#include "numpp/fft/fft.hpp"
#include "numpp/random/random.hpp"
#include "numpp/io/npy.hpp"
#include "numpp/io/npz.hpp"
#include "numpp/io/format.hpp"
#include "numpp/sorting/sorting.hpp"
#include "numpp/strings/strings.hpp"
#include "numpp/datetime/datetime.hpp"
#include "numpp/struct/struct.hpp"
#include "numpp/backend/backend.hpp"
